import {
  HomeIcon,
  TrophyIcon,
  ChatBubbleBottomCenterIcon,
  UserIcon,
  PlusIcon,
  ChartPieIcon,
  UsersIcon,
  DocumentTextIcon,
  Cog6ToothIcon,
  ShieldCheckIcon,
  ClipboardDocumentListIcon,
  FlagIcon,
  GlobeAltIcon,
} from "@heroicons/react/24/outline";

import { UserRole, AppTab, TabCategory, type MenuItem } from "../types/enums";

export const SIDEBAR_MENU: MenuItem[] = [
  {
    id: AppTab.HOME,
    label: "Home",
    icon: HomeIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/",
  },
  {
    id: AppTab.EXPLORE,
    label: "Explore",
    icon: GlobeAltIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/explore",
  },
  {
    id: AppTab.RANKING,
    label: "Ranking",
    icon: TrophyIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/ranking",
  },
  {
    id: AppTab.DIRECT,
    label: "Direct",
    icon: ChatBubbleBottomCenterIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/direct",
  },
  {
    id: AppTab.PROFILE,
    label: "Profile",
    icon: UserIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/profile",
  },
  {
    id: AppTab.CREATE,
    label: "Create",
    icon: PlusIcon,
    category: TabCategory.MAIN,
    roles: [UserRole.USER, UserRole.MODERATOR, UserRole.ADMIN],
    path: "/create",
  },

  // Admin tabs
  {
    id: AppTab.ADMIN_DASHBOARD,
    label: "Admin Dashboard",
    icon: ChartPieIcon,
    category: TabCategory.ADMIN,
    roles: [UserRole.ADMIN],
    path: "/admin",
  },
  {
    id: AppTab.USER_MANAGEMENT,
    label: "User Management",
    icon: UsersIcon,
    category: TabCategory.ADMIN,
    roles: [UserRole.ADMIN],
    path: "/admin/user-management",
  },
  {
    id: AppTab.POST_MANAGEMENT,
    label: "Post Management",
    icon: DocumentTextIcon,
    category: TabCategory.ADMIN,
    roles: [UserRole.ADMIN],
    path: "/admin/post-management",
  },
  {
    id: AppTab.ANALYTICS,
    label: "Analytics",
    icon: ChartPieIcon,
    category: TabCategory.ADMIN,
    roles: [UserRole.ADMIN],
    path: "/admin/analytics",
  },
  {
    id: AppTab.SYSTEM_SETTINGS,
    label: "System Settings",
    icon: Cog6ToothIcon,
    category: TabCategory.ADMIN,
    roles: [UserRole.ADMIN],
    path: "/admin/settings",
  },

  // Moderator tabs
  {
    id: AppTab.MOD_DASHBOARD,
    label: "Mod Dashboard",
    icon: ShieldCheckIcon,
    category: TabCategory.MODERATOR,
    roles: [UserRole.MODERATOR],
    path: "/moderator",
  },
  {
    id: AppTab.POST_REVIEW,
    label: "Post Review",
    icon: ClipboardDocumentListIcon,
    category: TabCategory.MODERATOR,
    roles: [UserRole.MODERATOR],
    path: "/moderator/post-review",
  },
  {
    id: AppTab.REPORTS,
    label: "Reports",
    icon: FlagIcon,
    category: TabCategory.MODERATOR,
    roles: [UserRole.MODERATOR],
    path: "/moderator/reports",
  },
];